import { afterEach, describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { buildApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { openDatabase } from '../src/database.js';
import { createLogger } from '../src/logger.js';
import { decryptSecret, deriveSecretKey } from '../src/secrets.js';
const cleanup: (() => unknown | Promise<unknown>)[] = [];
afterEach(async () => { for (const fn of cleanup.splice(0).reverse()) await fn(); });
const origin = 'http://127.0.0.1:5173';
async function setup() { const dir = mkdtempSync(join(tmpdir(), 'home-nvr-camera-')); cleanup.push(() => rmSync(dir, { recursive: true, force: true })); const database = openDatabase(dir); cleanup.push(() => database.close()); const config = loadConfig({ NVR_DATA_DIR: dir, NVR_SETUP_TOKEN: 'x'.repeat(40), NVR_SECRET_KEY: 'camera-secret-key-for-tests-long-enough' }); const app = await buildApp(config, { database, logger: createLogger('silent'), serveWeb: false }); cleanup.push(() => app.close()); const owner = await app.inject({ method: 'POST', url: '/api/v1/auth/setup', payload: { username: 'owner', password: 'a-very-strong-password', setupToken: config.setupToken } }); return { app, database, config, ownerCookie: String(owner.headers['set-cookie'] ?? '') }; }
async function addCamera(app: Awaited<ReturnType<typeof buildApp>>, cookie: string, name: string) { return app.inject({ method: 'POST', url: '/api/v1/cameras', headers: { origin, cookie }, payload: { name, location: 'Test', mainSourceUrl: `rtsp://admin:secret@${name.toLowerCase()}.local/live`, subSourceUrl: `rtsp://${name.toLowerCase()}.local/sub` } }); }
describe('camera CRUD và quyền', () => {
  it('mã hóa nguồn khi tạo/cập nhật và soft delete camera', async () => { const { app, database, config, ownerCookie } = await setup(); const created = await addCamera(app, ownerCookie, 'Front'); expect(created.statusCode).toBe(201); expect(created.body).not.toContain('rtsp'); const id = created.json().id; const before = database.db.prepare("SELECT source_ciphertext FROM camera_streams WHERE profile='main'").get() as any; expect(before.source_ciphertext).not.toContain('secret'); const patched = await app.inject({ method: 'PATCH', url: `/api/v1/cameras/${id}`, headers: { origin, cookie: ownerCookie }, payload: { mainSourceUrl: 'rtsp://admin:new-secret@front.local/new', subSourceUrl: null } }); expect(patched.statusCode).toBe(200); const after = database.db.prepare("SELECT source_ciphertext FROM camera_streams WHERE profile='main'").get() as any; expect(after.source_ciphertext).not.toBe(before.source_ciphertext); expect(decryptSecret(after.source_ciphertext, deriveSecretKey(config.secretKey))).toContain('new-secret'); expect(database.db.prepare("SELECT 1 FROM camera_streams WHERE profile='sub'").get()).toBeUndefined(); expect((await app.inject({ method: 'DELETE', url: `/api/v1/cameras/${id}`, headers: { origin, cookie: ownerCookie } })).statusCode).toBe(204); expect((await app.inject({ url: '/api/v1/cameras', headers: { cookie: ownerCookie } })).json()).toEqual([]); });
  it('guest chỉ thấy camera được cấp và không thể mutation', async () => { const { app, ownerCookie } = await setup(); const first = await addCamera(app, ownerCookie, 'Front'); await addCamera(app, ownerCookie, 'Back'); const expiresAt = new Date(Date.now() + 86_400_000).toISOString(); expect((await app.inject({ method: 'POST', url: '/api/v1/users', headers: { origin, cookie: ownerCookie }, payload: { username: 'guest', password: 'guest-password-strong', expiresAt, cameraIds: [first.json().id] } })).statusCode).toBe(201); const login = await app.inject({ method: 'POST', url: '/api/v1/auth/login', payload: { username: 'guest', password: 'guest-password-strong' } }); const guestCookie = String(login.headers['set-cookie'] ?? ''); const cameras = (await app.inject({ url: '/api/v1/cameras', headers: { cookie: guestCookie } })).json(); expect(cameras.map((camera: any) => camera.id)).toEqual([first.json().id]); expect((await app.inject({ method: 'POST', url: '/api/v1/cameras', headers: { origin, cookie: guestCookie }, payload: { name: 'Denied', mainSourceUrl: 'rtsp://camera/live' } })).statusCode).toBe(403); });
  it('owner cấu hình rule, tạo motion event và cập nhật settings qua API', async () => { const { app, ownerCookie } = await setup(); const camera = await addCamera(app, ownerCookie, 'Motion'); const id = camera.json().id; await app.inject({ method: 'PATCH', url: `/api/v1/cameras/${id}`, headers: { origin, cookie: ownerCookie }, payload: { recordingMode: 'event' } }); const rule = await app.inject({ method: 'PATCH', url: `/api/v1/cameras/${id}/event-rule`, headers: { origin, cookie: ownerCookie }, payload: { enabled: true, sensitivity: 50, preSeconds: 10, postSeconds: 20, schedule: { days: [0,1,2,3,4,5,6], start: '00:00', end: '24:00' } } }); expect(rule.statusCode).toBe(200); const motion = await app.inject({ method: 'POST', url: `/api/v1/cameras/${id}/motion`, headers: { origin, cookie: ownerCookie }, payload: { confidence: 0.8 } }); expect(motion.json().accepted).toBe(true); expect((await app.inject({ url: '/api/v1/events', headers: { cookie: ownerCookie } })).json()).toHaveLength(1); const settings = await app.inject({ method: 'PATCH', url: '/api/v1/settings', headers: { origin, cookie: ownerCookie }, payload: { timezone: 'Asia/Ho_Chi_Minh', retentionDays: 30, storageLimitBytes: null, remoteEnabled: false } }); expect(settings.json().retentionDays).toBe(30); });  it('từ chối request thiếu session, Origin hoặc URL RTSP hợp lệ', async () => { const { app, ownerCookie } = await setup(); expect((await app.inject({ method: 'POST', url: '/api/v1/cameras', payload: { name: 'x', mainSourceUrl: 'rtsp://camera/live' } })).statusCode).toBe(401); expect((await app.inject({ method: 'POST', url: '/api/v1/cameras', headers: { cookie: ownerCookie }, payload: { name: 'x', mainSourceUrl: 'rtsp://camera/live' } })).statusCode).toBe(403); expect((await app.inject({ method: 'POST', url: '/api/v1/cameras', headers: { origin, cookie: ownerCookie }, payload: { name: 'x', mainSourceUrl: 'http://camera/live' } })).statusCode).toBe(400); });
});
